vich_uploader:
    db_driver: orm

    mappings:
        recipes_image:
            uri_prefix: /img/recipes
            upload_destination: '%kernel.project_dir%/public/img/recipes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        users_image:
            uri_prefix: /img/users
            upload_destination: '%kernel.project_dir%/public/img/users'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer