vich_uploader:
    db_driver: orm

    mappings:
       recipes_image:
            uri_prefix: /img
            upload_destination: '%kernel.project_dir%/public/img'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        # users_image:
        #     uri_prefix: /img
        #     upload_destination: '%kernel.project_dir%/public/img'
        #     namer: Vich\UploaderBundle\Naming\SmartUniqueNamer